version: '3.8'
x-app_config: &backend_config
  image: voice:backend
  environment:
    ACTION_MAILER_HOST: http://backend:3001
    ACTION_MAILER_TLD_LENGTH: 1
    REDIS_URL: redis://redis:6379/0
    REDIS_URL_SIDEKIQ: redis://redis:6379/2
    REDIS_URL_ACTIONCABLE: redis://redis:6379/1
    RAILS_ENV: cypress
    SECRET_KEY_BASE: 8e0b7c1ba5619c20d3e7869c279a22aba3ebe71a47f8921447d02b8d0f39e02003be48158d1652e4a51e60053c5a17ba91dcc804d01ecf64018f4f87c275dae7
  depends_on:
    - db
    - redis
    - kafka
services:
  backend:
    <<: *backend_config
    ports:
      - 3000:3000
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '3000']
  frontend:
    build:
      context: ../../../../../voice-frontend
      dockerfile: Dockerfile.e2e
    environment:
      NEXT_PUBLIC_ACTIONCABLE_URL: http://localhost:3000/cable
      # NEXT_PUBLIC_BACKEND_URL: http://backend:3000
      # NEXT_PUBLIC_ACTIONCABLE_URL: ws://localhost:3000/cable
    ports:
      - 3001:3001
    environment:
      NEXT_PUBLIC_ACTIONCABLE_URL: ws://backend:3000/cable
    command: ['yarn', 'dev']
    logging:
      driver: none
  sidekiq:
    <<: *backend_config
    command: ['sidekiq']
  db:
    image: postgres:11.4-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging:
      driver: none
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    command: ['redis-server']
    logging:
      driver: none
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - 2181:2181
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "engage-event:1:1,rules-engine-response:1:1,user-action:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      # KAFKA_CREATE_TOPICS: "engage-event:1:1,rules-engine-response:1:1,user-action:1:1"
      # KAFKA_CREATE_TOPICS: 'topic_metadata:1:1'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # logging:
    #   driver: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
volumes:
  postgres:
  redis:
